# Generated by Django 4.2.5 on 2023-09-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zfunds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zuser',
            name='admin_id',
        ),
        migrations.RemoveField(
            model_name='zuser',
            name='advisor_id',
        ),
        migrations.RemoveField(
            model_name='zuser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='zuser',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zuser',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
