# Generated by Django 4.2.5 on 2023-09-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zfunds', '0003_zuser_user_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zuser',
            name='account_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CLIENT', 'Client'), ('ADVISOR', 'Advisor')], max_length=10),
        ),
    ]
