# Generated by Django 4.2.5 on 2023-09-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zfunds', '0005_alter_category_cid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cid',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
