# Generated by Django 4.2.5 on 2023-09-08 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zfunds', '0006_rename_cid_product_category_alter_product_pid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='user_id',
            new_name='client_id',
        ),
    ]
